# Generated by Django 3.2.6 on 2021-08-30 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_register', '0002_auto_20210830_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoption',
            old_name='product_description',
            new_name='option_description',
        ),
        migrations.RenameField(
            model_name='productoption',
            old_name='product_name',
            new_name='option_name',
        ),
    ]
